# Generated by Django 5.0.2 on 2024-04-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abrev', models.CharField(max_length=5)),
                ('descrip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_count', models.CharField(max_length=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.client')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product_client')),
                ('id_transactions_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactions_type')),
            ],
        ),
    ]
