# Generated by Django 5.0.2 on 2024-03-15 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_dept', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 966686))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 966686))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deparments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_country', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 966686))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 966686))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifications_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_ident_type', models.IntegerField()),
                ('ident_number', models.CharField(max_length=15)),
                ('id_exp_city', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('id_user', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('id_person', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 965620))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 964659))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 16, 45, 2, 964659))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
