# Generated by Django 5.0.2 on 2024-03-15 22:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 516236))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 516236))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Identifications_type',
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 516236)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='id_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.deparments'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 516236)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 517327)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 517327)),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 517327)),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='id_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.countries'),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 517327)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 516236)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='id_exp_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cities'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.user'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 516236)),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 515333)),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.persons'),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 515333)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 515333)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 2, 27, 515333)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='id_ident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.identification_type'),
        ),
    ]
